apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    owner: vasif
    email: vasifrehman@gail.com
spec:
  containers:
    - name: nginx
      image: nginx

